// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module MVAU_hls_0_Matrix_Vector_Activate_Stream_Batch (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in0_V_TVALID,
        weights_V_TVALID,
        out_V_TREADY,
        in0_V_TDATA,
        in0_V_TREADY,
        out_V_TDATA,
        out_V_TVALID,
        weights_V_TDATA,
        weights_V_TREADY
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter3_fsm_state4 = 2'd2;
parameter    ap_ST_iter4_fsm_state5 = 2'd2;
parameter    ap_ST_iter5_fsm_state6 = 2'd2;
parameter    ap_ST_iter6_fsm_state7 = 2'd2;
parameter    ap_ST_iter7_fsm_state8 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;
parameter    ap_ST_iter3_fsm_state0 = 2'd1;
parameter    ap_ST_iter4_fsm_state0 = 2'd1;
parameter    ap_ST_iter5_fsm_state0 = 2'd1;
parameter    ap_ST_iter6_fsm_state0 = 2'd1;
parameter    ap_ST_iter7_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in0_V_TVALID;
input   weights_V_TVALID;
input   out_V_TREADY;
input  [71:0] in0_V_TDATA;
output   in0_V_TREADY;
output  [7:0] out_V_TDATA;
output   out_V_TVALID;
input  [71:0] weights_V_TDATA;
output   weights_V_TREADY;

reg ap_idle;
reg in0_V_TREADY;
reg out_V_TVALID;
reg weights_V_TREADY;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state0;
reg   [1:0] ap_CS_iter3_fsm;
wire    ap_CS_iter3_fsm_state0;
reg   [1:0] ap_CS_iter4_fsm;
wire    ap_CS_iter4_fsm_state0;
reg   [1:0] ap_CS_iter5_fsm;
wire    ap_CS_iter5_fsm_state0;
reg   [1:0] ap_CS_iter6_fsm;
wire    ap_CS_iter6_fsm_state0;
reg   [1:0] ap_CS_iter7_fsm;
wire    ap_CS_iter7_fsm_state0;
wire   [0:0] icmp_ln249_fu_279_p2;
wire   [0:0] icmp_ln253_fu_291_p2;
reg    ap_predicate_op42_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_CS_iter1_fsm_state2;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_CS_iter6_fsm_state7;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_CS_iter5_fsm_state6;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_CS_iter4_fsm_state5;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_CS_iter3_fsm_state4;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_CS_iter2_fsm_state3;
reg   [0:0] icmp_ln249_reg_992;
reg   [0:0] icmp_ln249_reg_992_pp0_iter6_reg;
reg   [0:0] icmp_ln290_reg_1066;
reg   [0:0] icmp_ln290_reg_1066_pp0_iter6_reg;
reg    ap_predicate_op215_write_state8;
reg    ap_block_state8_pp0_stage0_iter7;
reg    ap_block_state8_io;
wire    ap_CS_iter7_fsm_state8;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [2:0] p_ZL7threshs_0_address0;
reg    p_ZL7threshs_0_ce0;
wire   [13:0] p_ZL7threshs_0_q0;
wire   [2:0] p_ZL7threshs_1_address0;
reg    p_ZL7threshs_1_ce0;
wire   [12:0] p_ZL7threshs_1_q0;
wire   [2:0] p_ZL7threshs_2_address0;
reg    p_ZL7threshs_2_ce0;
wire   [13:0] p_ZL7threshs_2_q0;
wire   [2:0] p_ZL7threshs_3_address0;
reg    p_ZL7threshs_3_ce0;
wire   [12:0] p_ZL7threshs_3_q0;
wire   [2:0] p_ZL7threshs_4_address0;
reg    p_ZL7threshs_4_ce0;
wire   [13:0] p_ZL7threshs_4_q0;
wire   [2:0] p_ZL7threshs_5_address0;
reg    p_ZL7threshs_5_ce0;
wire   [13:0] p_ZL7threshs_5_q0;
wire   [2:0] p_ZL7threshs_6_address0;
reg    p_ZL7threshs_6_ce0;
wire   [13:0] p_ZL7threshs_6_q0;
reg    in0_V_TDATA_blk_n;
reg    out_V_TDATA_blk_n;
reg    weights_V_TDATA_blk_n;
reg   [31:0] nf_2_reg_987;
reg   [31:0] nf_2_reg_987_pp0_iter1_reg;
reg   [31:0] nf_2_reg_987_pp0_iter2_reg;
reg   [31:0] nf_2_reg_987_pp0_iter3_reg;
reg   [31:0] nf_2_reg_987_pp0_iter4_reg;
wire   [0:0] icmp_ln249_reg_992_pp0_iter0_reg;
reg   [0:0] icmp_ln249_reg_992_pp0_iter1_reg;
reg   [0:0] icmp_ln249_reg_992_pp0_iter2_reg;
reg   [0:0] icmp_ln249_reg_992_pp0_iter3_reg;
reg   [0:0] icmp_ln249_reg_992_pp0_iter4_reg;
reg   [0:0] icmp_ln249_reg_992_pp0_iter5_reg;
wire   [71:0] tmp_fu_310_p5;
wire   [1:0] trunc_ln257_fu_322_p1;
wire   [0:0] icmp_ln272_fu_341_p2;
reg   [0:0] icmp_ln272_reg_1016;
reg   [0:0] icmp_ln272_reg_1016_pp0_iter1_reg;
reg   [0:0] icmp_ln272_reg_1016_pp0_iter2_reg;
reg   [0:0] icmp_ln272_reg_1016_pp0_iter3_reg;
reg   [0:0] icmp_ln272_reg_1016_pp0_iter4_reg;
wire   [7:0] local_temp_V_fu_347_p1;
reg  signed [7:0] local_temp_V_reg_1021;
reg   [7:0] local_temp_V_9_reg_1026;
reg   [7:0] local_temp_V_9_reg_1026_pp0_iter1_reg;
reg  signed [7:0] local_temp_V_9_reg_1026_pp0_iter2_reg;
reg   [7:0] local_temp_V_10_reg_1031;
reg  signed [7:0] local_temp_V_10_reg_1031_pp0_iter1_reg;
reg   [7:0] local_temp_V_11_reg_1036;
reg   [7:0] local_temp_V_11_reg_1036_pp0_iter1_reg;
reg  signed [7:0] local_temp_V_11_reg_1036_pp0_iter2_reg;
reg  signed [7:0] local_temp_V_12_reg_1041;
reg   [7:0] local_temp_V_13_reg_1046;
reg   [7:0] local_temp_V_13_reg_1046_pp0_iter1_reg;
reg  signed [7:0] local_temp_V_13_reg_1046_pp0_iter2_reg;
reg   [7:0] local_temp_V_14_reg_1051;
reg   [7:0] local_temp_V_14_reg_1051_pp0_iter1_reg;
reg  signed [7:0] local_temp_V_14_reg_1051_pp0_iter2_reg;
reg   [7:0] local_temp_V_15_reg_1056;
reg  signed [7:0] local_temp_V_15_reg_1056_pp0_iter1_reg;
reg  signed [7:0] local_temp_V_16_reg_1061;
wire   [0:0] icmp_ln290_fu_437_p2;
reg   [0:0] icmp_ln290_reg_1066_pp0_iter1_reg;
reg   [0:0] icmp_ln290_reg_1066_pp0_iter2_reg;
reg   [0:0] icmp_ln290_reg_1066_pp0_iter3_reg;
reg   [0:0] icmp_ln290_reg_1066_pp0_iter4_reg;
reg   [0:0] icmp_ln290_reg_1066_pp0_iter5_reg;
reg   [7:0] r_V_1_reg_1080;
reg   [7:0] r_V_1_reg_1080_pp0_iter2_reg;
reg   [7:0] r_V_2_reg_1085;
reg   [7:0] r_V_3_reg_1090;
reg   [7:0] r_V_3_reg_1090_pp0_iter2_reg;
reg   [7:0] r_V_5_reg_1105;
reg   [7:0] r_V_5_reg_1105_pp0_iter2_reg;
reg   [7:0] r_V_6_reg_1110;
reg   [7:0] r_V_6_reg_1110_pp0_iter2_reg;
reg   [7:0] r_V_7_reg_1115;
wire  signed [16:0] grp_fu_889_p3;
reg  signed [16:0] add_ln840_4_reg_1180;
wire  signed [17:0] grp_fu_924_p3;
reg  signed [17:0] add_ln840_2_reg_1195;
wire   [18:0] add_ln840_7_fu_676_p2;
reg   [18:0] add_ln840_7_reg_1200;
wire   [18:0] add_ln840_8_fu_700_p2;
reg   [18:0] add_ln840_8_reg_1240;
reg   [13:0] p_ZL7threshs_0_load_reg_1251;
reg   [12:0] p_ZL7threshs_1_load_reg_1256;
reg   [13:0] p_ZL7threshs_2_load_reg_1261;
reg   [12:0] p_ZL7threshs_3_load_reg_1266;
reg   [13:0] p_ZL7threshs_4_load_reg_1271;
reg   [13:0] p_ZL7threshs_5_load_reg_1276;
reg   [13:0] p_ZL7threshs_6_load_reg_1281;
wire   [71:0] ap_phi_reg_pp0_iter0_inElem_1_reg_242;
reg   [71:0] ap_phi_reg_pp0_iter1_inElem_1_reg_242;
wire   [63:0] idxprom2_i_fu_682_p1;
reg   [31:0] sf_fu_104;
wire   [31:0] sf_2_fu_431_p2;
wire    ap_loop_init;
reg   [31:0] ap_sig_allocacmp_sf_1;
reg   [21:0] i_fu_108;
wire   [21:0] i_2_fu_285_p2;
reg   [21:0] ap_sig_allocacmp_i_1;
reg   [18:0] add_i5_i3_870_fu_112;
reg   [18:0] ap_sig_allocacmp_add_i5_i3_870_load;
reg   [71:0] inputBuf_V_fu_116;
reg   [71:0] inputBuf_V_1_fu_120;
reg   [71:0] inputBuf_V_2_fu_124;
reg   [31:0] nf_1_fu_128;
wire   [31:0] nf_3_fu_460_p3;
reg   [31:0] ap_sig_allocacmp_nf_2;
wire   [1:0] tmp_fu_310_p4;
wire   [31:0] nf_fu_448_p2;
wire   [0:0] icmp_ln302_fu_454_p2;
wire   [7:0] r_V_fu_483_p1;
wire   [7:0] r_V_4_fu_524_p4;
wire   [7:0] r_V_8_fu_571_p4;
wire   [7:0] ret_V_1_fu_606_p0;
wire  signed [15:0] ret_V_1_fu_606_p2;
wire   [7:0] ret_V_3_fu_622_p0;
wire  signed [15:0] ret_V_3_fu_622_p2;
wire   [7:0] ret_V_5_fu_638_p0;
wire  signed [15:0] ret_V_5_fu_638_p2;
wire  signed [16:0] grp_fu_897_p3;
wire  signed [16:0] grp_fu_906_p3;
wire  signed [17:0] grp_fu_915_p3;
wire  signed [18:0] sext_ln840_6_fu_673_p1;
wire  signed [18:0] sext_ln840_4_fu_670_p1;
wire  signed [18:0] sext_ln840_3_fu_692_p1;
wire  signed [18:0] grp_fu_932_p3;
(* use_dsp48 = "no" *) wire   [18:0] add_ln840_3_fu_695_p2;
wire  signed [18:0] sext_ln1039_fu_710_p1;
wire   [0:0] icmp_ln1039_fu_713_p2;
wire   [0:0] result_V_fu_718_p2;
wire  signed [18:0] sext_ln1039_1_fu_728_p1;
wire   [0:0] icmp_ln1039_1_fu_731_p2;
wire   [0:0] xor_ln1039_fu_736_p2;
wire  signed [18:0] sext_ln1039_2_fu_746_p1;
wire   [0:0] icmp_ln1039_2_fu_749_p2;
wire   [0:0] xor_ln1039_1_fu_754_p2;
wire   [18:0] zext_ln1039_fu_764_p1;
wire   [0:0] icmp_ln1039_3_fu_767_p2;
wire   [0:0] xor_ln1039_2_fu_772_p2;
wire   [18:0] zext_ln1039_1_fu_782_p1;
wire   [0:0] icmp_ln1039_4_fu_785_p2;
wire   [0:0] xor_ln1039_3_fu_790_p2;
wire   [18:0] zext_ln1039_2_fu_800_p1;
wire   [0:0] icmp_ln1039_5_fu_803_p2;
wire   [0:0] xor_ln1039_4_fu_808_p2;
wire   [18:0] zext_ln1039_3_fu_818_p1;
wire   [0:0] icmp_ln1039_6_fu_821_p2;
wire   [0:0] xor_ln1039_5_fu_826_p2;
wire   [1:0] zext_ln215_fu_724_p1;
wire   [1:0] zext_ln218_1_fu_760_p1;
wire   [1:0] add_ln840_9_fu_836_p2;
wire   [1:0] zext_ln218_fu_742_p1;
wire   [1:0] add_ln840_10_fu_842_p2;
wire   [1:0] zext_ln218_2_fu_778_p1;
wire   [1:0] zext_ln218_3_fu_796_p1;
wire   [1:0] add_ln840_11_fu_852_p2;
wire   [1:0] zext_ln218_4_fu_814_p1;
wire   [1:0] zext_ln840_fu_832_p1;
wire   [1:0] add_ln840_12_fu_862_p2;
wire   [2:0] zext_ln840_3_fu_868_p1;
wire   [2:0] zext_ln840_2_fu_858_p1;
wire   [2:0] add_ln840_13_fu_872_p2;
wire   [2:0] zext_ln840_1_fu_848_p1;
wire   [2:0] result_V_2_fu_878_p2;
wire   [7:0] grp_fu_889_p0;
wire   [7:0] grp_fu_897_p0;
wire   [7:0] grp_fu_906_p0;
wire   [7:0] grp_fu_915_p0;
wire   [7:0] grp_fu_924_p0;
wire   [7:0] grp_fu_932_p0;
wire  signed [18:0] grp_fu_932_p2;
reg    grp_fu_889_ce;
reg    grp_fu_897_ce;
reg    grp_fu_906_ce;
reg    grp_fu_915_ce;
reg    grp_fu_924_ce;
reg    grp_fu_932_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg   [1:0] ap_NS_iter3_fsm;
reg   [1:0] ap_NS_iter4_fsm;
reg   [1:0] ap_NS_iter5_fsm;
reg   [1:0] ap_NS_iter6_fsm;
reg   [1:0] ap_NS_iter7_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
wire    ap_ST_iter1_fsm_state2_blk;
wire    ap_ST_iter2_fsm_state3_blk;
wire    ap_ST_iter3_fsm_state4_blk;
wire    ap_ST_iter4_fsm_state5_blk;
wire    ap_ST_iter5_fsm_state6_blk;
wire    ap_ST_iter6_fsm_state7_blk;
reg    ap_ST_iter7_fsm_state8_blk;
wire    ap_start_int;
wire   [15:0] grp_fu_889_p00;
wire   [15:0] grp_fu_897_p00;
wire   [15:0] grp_fu_906_p00;
wire   [15:0] grp_fu_915_p00;
wire   [15:0] grp_fu_924_p00;
wire   [15:0] grp_fu_932_p00;
wire   [15:0] ret_V_1_fu_606_p00;
wire   [15:0] ret_V_3_fu_622_p00;
wire   [15:0] ret_V_5_fu_638_p00;
reg    ap_condition_1059;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_CS_iter3_fsm = 2'd1;
#0 ap_CS_iter4_fsm = 2'd1;
#0 ap_CS_iter5_fsm = 2'd1;
#0 ap_CS_iter6_fsm = 2'd1;
#0 ap_CS_iter7_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
end

MVAU_hls_0_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_0_ROM_AUTO_1R #(
    .DataWidth( 14 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
p_ZL7threshs_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_0_address0),
    .ce0(p_ZL7threshs_0_ce0),
    .q0(p_ZL7threshs_0_q0)
);

MVAU_hls_0_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_1_ROM_AUTO_1R #(
    .DataWidth( 13 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
p_ZL7threshs_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_1_address0),
    .ce0(p_ZL7threshs_1_ce0),
    .q0(p_ZL7threshs_1_q0)
);

MVAU_hls_0_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_2_ROM_AUTO_1R #(
    .DataWidth( 14 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
p_ZL7threshs_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_2_address0),
    .ce0(p_ZL7threshs_2_ce0),
    .q0(p_ZL7threshs_2_q0)
);

MVAU_hls_0_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_3_ROM_AUTO_1R #(
    .DataWidth( 13 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
p_ZL7threshs_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_3_address0),
    .ce0(p_ZL7threshs_3_ce0),
    .q0(p_ZL7threshs_3_q0)
);

MVAU_hls_0_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_4_ROM_AUTO_1R #(
    .DataWidth( 14 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
p_ZL7threshs_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_4_address0),
    .ce0(p_ZL7threshs_4_ce0),
    .q0(p_ZL7threshs_4_q0)
);

MVAU_hls_0_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_5_ROM_AUTO_1R #(
    .DataWidth( 14 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
p_ZL7threshs_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_5_address0),
    .ce0(p_ZL7threshs_5_ce0),
    .q0(p_ZL7threshs_5_q0)
);

MVAU_hls_0_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_6_ROM_AUTO_1R #(
    .DataWidth( 14 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
p_ZL7threshs_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_6_address0),
    .ce0(p_ZL7threshs_6_ce0),
    .q0(p_ZL7threshs_6_q0)
);

MVAU_hls_0_mux_32_72_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 72 ),
    .din1_WIDTH( 72 ),
    .din2_WIDTH( 72 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 72 ))
mux_32_72_1_1_U1(
    .din0(inputBuf_V_fu_116),
    .din1(inputBuf_V_1_fu_120),
    .din2(inputBuf_V_2_fu_124),
    .din3(tmp_fu_310_p4),
    .dout(tmp_fu_310_p5)
);

MVAU_hls_0_mul_8ns_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8s_16_1_1_U2(
    .din0(ret_V_1_fu_606_p0),
    .din1(local_temp_V_9_reg_1026_pp0_iter2_reg),
    .dout(ret_V_1_fu_606_p2)
);

MVAU_hls_0_mul_8ns_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8s_16_1_1_U3(
    .din0(ret_V_3_fu_622_p0),
    .din1(local_temp_V_11_reg_1036_pp0_iter2_reg),
    .dout(ret_V_3_fu_622_p2)
);

MVAU_hls_0_mul_8ns_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8s_16_1_1_U4(
    .din0(ret_V_5_fu_638_p0),
    .din1(local_temp_V_13_reg_1046_pp0_iter2_reg),
    .dout(ret_V_5_fu_638_p2)
);

MVAU_hls_0_mac_muladd_8ns_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8s_16s_17_4_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_889_p0),
    .din1(local_temp_V_reg_1021),
    .din2(ret_V_3_fu_622_p2),
    .ce(grp_fu_889_ce),
    .dout(grp_fu_889_p3)
);

MVAU_hls_0_mac_muladd_8ns_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8s_16s_17_4_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_897_p0),
    .din1(local_temp_V_12_reg_1041),
    .din2(ret_V_5_fu_638_p2),
    .ce(grp_fu_897_ce),
    .dout(grp_fu_897_p3)
);

MVAU_hls_0_mac_muladd_8ns_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8s_16s_17_4_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_906_p0),
    .din1(local_temp_V_16_reg_1061),
    .din2(ret_V_1_fu_606_p2),
    .ce(grp_fu_906_ce),
    .dout(grp_fu_906_p3)
);

MVAU_hls_0_mac_muladd_8ns_8s_17s_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 18 ))
mac_muladd_8ns_8s_17s_18_4_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_915_p0),
    .din1(local_temp_V_10_reg_1031_pp0_iter1_reg),
    .din2(grp_fu_906_p3),
    .ce(grp_fu_915_ce),
    .dout(grp_fu_915_p3)
);

MVAU_hls_0_mac_muladd_8ns_8s_17s_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 18 ))
mac_muladd_8ns_8s_17s_18_4_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_924_p0),
    .din1(local_temp_V_15_reg_1056_pp0_iter1_reg),
    .din2(grp_fu_897_p3),
    .ce(grp_fu_924_ce),
    .dout(grp_fu_924_p3)
);

MVAU_hls_0_mac_muladd_8ns_8s_19s_19_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 19 ))
mac_muladd_8ns_8s_19s_19_4_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_932_p0),
    .din1(local_temp_V_14_reg_1051_pp0_iter2_reg),
    .din2(grp_fu_932_p2),
    .ce(grp_fu_932_ce),
    .dout(grp_fu_932_p3)
);

MVAU_hls_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter3_fsm <= ap_ST_iter3_fsm_state0;
    end else begin
        ap_CS_iter3_fsm <= ap_NS_iter3_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter4_fsm <= ap_ST_iter4_fsm_state0;
    end else begin
        ap_CS_iter4_fsm <= ap_NS_iter4_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter5_fsm <= ap_ST_iter5_fsm_state0;
    end else begin
        ap_CS_iter5_fsm <= ap_NS_iter5_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter6_fsm <= ap_ST_iter6_fsm_state0;
    end else begin
        ap_CS_iter6_fsm <= ap_NS_iter6_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter7_fsm <= ap_ST_iter7_fsm_state0;
    end else begin
        ap_CS_iter7_fsm <= ap_NS_iter7_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0))) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b1 == ap_CS_iter7_fsm_state8))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0))) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b0) & (1'b1 == ap_CS_iter7_fsm_state8))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= 1'b0;
    end else if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter6_fsm_state7))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_279_p2 == 1'd0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln253_fu_291_p2 == 1'd0) & (icmp_ln249_fu_279_p2 == 1'd0))) begin
        ap_phi_reg_pp0_iter1_inElem_1_reg_242 <= tmp_fu_310_p5;
    end else if (((~(trunc_ln257_fu_322_p1 == 2'd1) & ~(trunc_ln257_fu_322_p1 == 2'd0) & ~((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_279_p2 == 1'd0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln253_fu_291_p2 == 1'd1) & (icmp_ln249_fu_279_p2 == 1'd0)) | (~((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_279_p2 == 1'd0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln253_fu_291_p2 == 1'd1) & (icmp_ln249_fu_279_p2 == 1'd0) & (trunc_ln257_fu_322_p1 == 2'd1)) | (~((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_279_p2 == 1'd0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln253_fu_291_p2 == 1'd1) & (icmp_ln249_fu_279_p2 == 1'd0) & (trunc_ln257_fu_322_p1 == 2'd0)))) begin
        ap_phi_reg_pp0_iter1_inElem_1_reg_242 <= in0_V_TDATA;
    end else if ((~((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_279_p2 == 1'd0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_phi_reg_pp0_iter1_inElem_1_reg_242 <= ap_phi_reg_pp0_iter0_inElem_1_reg_242;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1059)) begin
        if ((icmp_ln249_fu_279_p2 == 1'd0)) begin
            i_fu_108 <= i_2_fu_285_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_108 <= 22'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1059)) begin
        if (((icmp_ln249_fu_279_p2 == 1'd0) & (icmp_ln290_fu_437_p2 == 1'd1))) begin
            nf_1_fu_128 <= nf_3_fu_460_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            nf_1_fu_128 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1059)) begin
        if (((icmp_ln249_fu_279_p2 == 1'd0) & (icmp_ln290_fu_437_p2 == 1'd1))) begin
            sf_fu_104 <= 32'd0;
        end else if (((icmp_ln249_fu_279_p2 == 1'd0) & (icmp_ln290_fu_437_p2 == 1'd0))) begin
            sf_fu_104 <= sf_2_fu_431_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            sf_fu_104 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter6_fsm_state7) & (icmp_ln249_reg_992_pp0_iter5_reg == 1'd0))) begin
        add_i5_i3_870_fu_112 <= add_ln840_8_fu_700_p2;
        add_ln840_8_reg_1240 <= add_ln840_8_fu_700_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter5_fsm_state6) & (icmp_ln249_reg_992_pp0_iter4_reg == 1'd0))) begin
        add_ln840_2_reg_1195 <= grp_fu_924_p3;
        add_ln840_7_reg_1200 <= add_ln840_7_fu_676_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter4_fsm_state5) & (icmp_ln249_reg_992_pp0_iter3_reg == 1'd0))) begin
        add_ln840_4_reg_1180 <= grp_fu_889_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_279_p2 == 1'd0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln249_reg_992 <= icmp_ln249_fu_279_p2;
        nf_2_reg_987 <= ap_sig_allocacmp_nf_2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln249_reg_992_pp0_iter1_reg <= icmp_ln249_reg_992;
        icmp_ln272_reg_1016_pp0_iter1_reg <= icmp_ln272_reg_1016;
        icmp_ln290_reg_1066_pp0_iter1_reg <= icmp_ln290_reg_1066;
        local_temp_V_10_reg_1031_pp0_iter1_reg <= local_temp_V_10_reg_1031;
        local_temp_V_11_reg_1036_pp0_iter1_reg <= local_temp_V_11_reg_1036;
        local_temp_V_13_reg_1046_pp0_iter1_reg <= local_temp_V_13_reg_1046;
        local_temp_V_14_reg_1051_pp0_iter1_reg <= local_temp_V_14_reg_1051;
        local_temp_V_15_reg_1056_pp0_iter1_reg <= local_temp_V_15_reg_1056;
        local_temp_V_9_reg_1026_pp0_iter1_reg <= local_temp_V_9_reg_1026;
        nf_2_reg_987_pp0_iter1_reg <= nf_2_reg_987;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln249_reg_992_pp0_iter2_reg <= icmp_ln249_reg_992_pp0_iter1_reg;
        icmp_ln272_reg_1016_pp0_iter2_reg <= icmp_ln272_reg_1016_pp0_iter1_reg;
        icmp_ln290_reg_1066_pp0_iter2_reg <= icmp_ln290_reg_1066_pp0_iter1_reg;
        local_temp_V_11_reg_1036_pp0_iter2_reg <= local_temp_V_11_reg_1036_pp0_iter1_reg;
        local_temp_V_13_reg_1046_pp0_iter2_reg <= local_temp_V_13_reg_1046_pp0_iter1_reg;
        local_temp_V_14_reg_1051_pp0_iter2_reg <= local_temp_V_14_reg_1051_pp0_iter1_reg;
        local_temp_V_9_reg_1026_pp0_iter2_reg <= local_temp_V_9_reg_1026_pp0_iter1_reg;
        nf_2_reg_987_pp0_iter2_reg <= nf_2_reg_987_pp0_iter1_reg;
        r_V_1_reg_1080_pp0_iter2_reg <= r_V_1_reg_1080;
        r_V_3_reg_1090_pp0_iter2_reg <= r_V_3_reg_1090;
        r_V_5_reg_1105_pp0_iter2_reg <= r_V_5_reg_1105;
        r_V_6_reg_1110_pp0_iter2_reg <= r_V_6_reg_1110;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        icmp_ln249_reg_992_pp0_iter3_reg <= icmp_ln249_reg_992_pp0_iter2_reg;
        icmp_ln272_reg_1016_pp0_iter3_reg <= icmp_ln272_reg_1016_pp0_iter2_reg;
        icmp_ln290_reg_1066_pp0_iter3_reg <= icmp_ln290_reg_1066_pp0_iter2_reg;
        nf_2_reg_987_pp0_iter3_reg <= nf_2_reg_987_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        icmp_ln249_reg_992_pp0_iter4_reg <= icmp_ln249_reg_992_pp0_iter3_reg;
        icmp_ln272_reg_1016_pp0_iter4_reg <= icmp_ln272_reg_1016_pp0_iter3_reg;
        icmp_ln290_reg_1066_pp0_iter4_reg <= icmp_ln290_reg_1066_pp0_iter3_reg;
        nf_2_reg_987_pp0_iter4_reg <= nf_2_reg_987_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter5_fsm_state6))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        icmp_ln249_reg_992_pp0_iter5_reg <= icmp_ln249_reg_992_pp0_iter4_reg;
        icmp_ln290_reg_1066_pp0_iter5_reg <= icmp_ln290_reg_1066_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter6_fsm_state7))) begin
        icmp_ln249_reg_992_pp0_iter6_reg <= icmp_ln249_reg_992_pp0_iter5_reg;
        icmp_ln290_reg_1066_pp0_iter6_reg <= icmp_ln290_reg_1066_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_279_p2 == 1'd0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_279_p2 == 1'd0))) begin
        icmp_ln272_reg_1016 <= icmp_ln272_fu_341_p2;
        icmp_ln290_reg_1066 <= icmp_ln290_fu_437_p2;
        local_temp_V_10_reg_1031 <= {{weights_V_TDATA[23:16]}};
        local_temp_V_11_reg_1036 <= {{weights_V_TDATA[31:24]}};
        local_temp_V_12_reg_1041 <= {{weights_V_TDATA[39:32]}};
        local_temp_V_13_reg_1046 <= {{weights_V_TDATA[47:40]}};
        local_temp_V_14_reg_1051 <= {{weights_V_TDATA[55:48]}};
        local_temp_V_15_reg_1056 <= {{weights_V_TDATA[63:56]}};
        local_temp_V_16_reg_1061 <= {{weights_V_TDATA[71:64]}};
        local_temp_V_9_reg_1026 <= {{weights_V_TDATA[15:8]}};
        local_temp_V_reg_1021 <= local_temp_V_fu_347_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_279_p2 == 1'd0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln253_fu_291_p2 == 1'd1) & (icmp_ln249_fu_279_p2 == 1'd0) & (trunc_ln257_fu_322_p1 == 2'd1))) begin
        inputBuf_V_1_fu_120 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~(trunc_ln257_fu_322_p1 == 2'd1) & ~(trunc_ln257_fu_322_p1 == 2'd0) & ~((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_279_p2 == 1'd0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln253_fu_291_p2 == 1'd1) & (icmp_ln249_fu_279_p2 == 1'd0))) begin
        inputBuf_V_2_fu_124 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_279_p2 == 1'd0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln253_fu_291_p2 == 1'd1) & (icmp_ln249_fu_279_p2 == 1'd0) & (trunc_ln257_fu_322_p1 == 2'd0))) begin
        inputBuf_V_fu_116 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter6_fsm_state7) & (icmp_ln290_reg_1066_pp0_iter5_reg == 1'd1) & (icmp_ln249_reg_992_pp0_iter5_reg == 1'd0))) begin
        p_ZL7threshs_0_load_reg_1251 <= p_ZL7threshs_0_q0;
        p_ZL7threshs_1_load_reg_1256 <= p_ZL7threshs_1_q0;
        p_ZL7threshs_2_load_reg_1261 <= p_ZL7threshs_2_q0;
        p_ZL7threshs_3_load_reg_1266 <= p_ZL7threshs_3_q0;
        p_ZL7threshs_4_load_reg_1271 <= p_ZL7threshs_4_q0;
        p_ZL7threshs_5_load_reg_1276 <= p_ZL7threshs_5_q0;
        p_ZL7threshs_6_load_reg_1281 <= p_ZL7threshs_6_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2) & (icmp_ln249_reg_992_pp0_iter0_reg == 1'd0))) begin
        r_V_1_reg_1080 <= {{ap_phi_reg_pp0_iter1_inElem_1_reg_242[15:8]}};
        r_V_2_reg_1085 <= {{ap_phi_reg_pp0_iter1_inElem_1_reg_242[23:16]}};
        r_V_3_reg_1090 <= {{ap_phi_reg_pp0_iter1_inElem_1_reg_242[31:24]}};
        r_V_5_reg_1105 <= {{ap_phi_reg_pp0_iter1_inElem_1_reg_242[47:40]}};
        r_V_6_reg_1110 <= {{ap_phi_reg_pp0_iter1_inElem_1_reg_242[55:48]}};
        r_V_7_reg_1115 <= {{ap_phi_reg_pp0_iter1_inElem_1_reg_242[63:56]}};
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_279_p2 == 1'd0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)))) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_iter1_fsm_state2_blk = 1'b0;

assign ap_ST_iter2_fsm_state3_blk = 1'b0;

assign ap_ST_iter3_fsm_state4_blk = 1'b0;

assign ap_ST_iter4_fsm_state5_blk = 1'b0;

assign ap_ST_iter5_fsm_state6_blk = 1'b0;

assign ap_ST_iter6_fsm_state7_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) begin
        ap_ST_iter7_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_iter7_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_279_p2 == 1'd0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_279_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0))) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b1 == ap_CS_iter7_fsm_state8))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter7_fsm_state0) & (1'b1 == ap_CS_iter6_fsm_state0) & (1'b1 == ap_CS_iter5_fsm_state0) & (1'b1 == ap_CS_iter4_fsm_state0) & (1'b1 == ap_CS_iter3_fsm_state0) & (1'b1 == ap_CS_iter2_fsm_state0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_279_p2 == 1'd0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter6_fsm_state7) & (icmp_ln249_reg_992_pp0_iter5_reg == 1'd0))) begin
        ap_sig_allocacmp_add_i5_i3_870_load = add_ln840_8_fu_700_p2;
    end else begin
        ap_sig_allocacmp_add_i5_i3_870_load = add_i5_i3_870_fu_112;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 22'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_108;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_nf_2 = 32'd0;
    end else begin
        ap_sig_allocacmp_nf_2 = nf_1_fu_128;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_sf_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_sf_1 = sf_fu_104;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2)))) begin
        grp_fu_889_ce = 1'b1;
    end else begin
        grp_fu_889_ce = 1'b0;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2)))) begin
        grp_fu_897_ce = 1'b1;
    end else begin
        grp_fu_897_ce = 1'b0;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2)))) begin
        grp_fu_906_ce = 1'b1;
    end else begin
        grp_fu_906_ce = 1'b0;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter5_fsm_state6)))) begin
        grp_fu_915_ce = 1'b1;
    end else begin
        grp_fu_915_ce = 1'b0;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter5_fsm_state6)))) begin
        grp_fu_924_ce = 1'b1;
    end else begin
        grp_fu_924_ce = 1'b0;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter5_fsm_state6)) | (~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter6_fsm_state7)))) begin
        grp_fu_932_ce = 1'b1;
    end else begin
        grp_fu_932_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op42_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b1))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_279_p2 == 1'd0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0))))) & (ap_predicate_op42_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        in0_V_TREADY = 1'b1;
    end else begin
        in0_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter7_fsm_state8) & (ap_predicate_op215_write_state8 == 1'b1))) begin
        out_V_TDATA_blk_n = out_V_TREADY;
    end else begin
        out_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0))) & (1'b1 == ap_CS_iter7_fsm_state8) & (ap_predicate_op215_write_state8 == 1'b1))) begin
        out_V_TVALID = 1'b1;
    end else begin
        out_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter5_fsm_state6))) begin
        p_ZL7threshs_0_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter5_fsm_state6))) begin
        p_ZL7threshs_1_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter5_fsm_state6))) begin
        p_ZL7threshs_2_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter5_fsm_state6))) begin
        p_ZL7threshs_3_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter5_fsm_state6))) begin
        p_ZL7threshs_4_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter5_fsm_state6))) begin
        p_ZL7threshs_5_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter5_fsm_state6))) begin
        p_ZL7threshs_6_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_279_p2 == 1'd0) & (ap_start_int == 1'b1))) begin
        weights_V_TDATA_blk_n = weights_V_TVALID;
    end else begin
        weights_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_279_p2 == 1'd0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_279_p2 == 1'd0))) begin
        weights_V_TREADY = 1'b1;
    end else begin
        weights_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & ~((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_279_p2 == 1'd0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & ((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_279_p2 == 1'd0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_279_p2 == 1'd0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b0 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter3_fsm)
        ap_ST_iter3_fsm_state4 : begin
            if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b0 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end
        end
        ap_ST_iter3_fsm_state0 : begin
            if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter3_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter4_fsm)
        ap_ST_iter4_fsm_state5 : begin
            if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end else if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b0 == ap_CS_iter3_fsm_state4))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state0;
            end else begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end
        end
        ap_ST_iter4_fsm_state0 : begin
            if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end else begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter4_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter5_fsm)
        ap_ST_iter5_fsm_state6 : begin
            if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state6;
            end else if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b0 == ap_CS_iter4_fsm_state5))) begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state0;
            end else begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state6;
            end
        end
        ap_ST_iter5_fsm_state0 : begin
            if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state6;
            end else begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter5_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter6_fsm)
        ap_ST_iter6_fsm_state7 : begin
            if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter5_fsm_state6))) begin
                ap_NS_iter6_fsm = ap_ST_iter6_fsm_state7;
            end else if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b0 == ap_CS_iter5_fsm_state6))) begin
                ap_NS_iter6_fsm = ap_ST_iter6_fsm_state0;
            end else begin
                ap_NS_iter6_fsm = ap_ST_iter6_fsm_state7;
            end
        end
        ap_ST_iter6_fsm_state0 : begin
            if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter5_fsm_state6))) begin
                ap_NS_iter6_fsm = ap_ST_iter6_fsm_state7;
            end else begin
                ap_NS_iter6_fsm = ap_ST_iter6_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter6_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter7_fsm)
        ap_ST_iter7_fsm_state8 : begin
            if ((~((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0))) & (1'b0 == ap_CS_iter6_fsm_state7))) begin
                ap_NS_iter7_fsm = ap_ST_iter7_fsm_state0;
            end else if (((~((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0))) & (1'b1 == ap_CS_iter7_fsm_state8) & (icmp_ln249_reg_992_pp0_iter6_reg == 1'd1)) | (~((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0))) & (1'b1 == ap_CS_iter6_fsm_state7)))) begin
                ap_NS_iter7_fsm = ap_ST_iter7_fsm_state8;
            end else begin
                ap_NS_iter7_fsm = ap_ST_iter7_fsm_state8;
            end
        end
        ap_ST_iter7_fsm_state0 : begin
            if ((~((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter6_fsm_state7))) begin
                ap_NS_iter7_fsm = ap_ST_iter7_fsm_state8;
            end else begin
                ap_NS_iter7_fsm = ap_ST_iter7_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter7_fsm = 'bx;
        end
    endcase
end

assign add_ln840_10_fu_842_p2 = (add_ln840_9_fu_836_p2 + zext_ln218_fu_742_p1);

assign add_ln840_11_fu_852_p2 = (zext_ln218_2_fu_778_p1 + zext_ln218_3_fu_796_p1);

assign add_ln840_12_fu_862_p2 = (zext_ln218_4_fu_814_p1 + zext_ln840_fu_832_p1);

assign add_ln840_13_fu_872_p2 = (zext_ln840_3_fu_868_p1 + zext_ln840_2_fu_858_p1);

assign add_ln840_3_fu_695_p2 = ($signed(sext_ln840_3_fu_692_p1) + $signed(grp_fu_932_p3));

assign add_ln840_7_fu_676_p2 = ($signed(sext_ln840_6_fu_673_p1) + $signed(sext_ln840_4_fu_670_p1));

assign add_ln840_8_fu_700_p2 = (add_ln840_7_reg_1200 + add_ln840_3_fu_695_p2);

assign add_ln840_9_fu_836_p2 = (zext_ln215_fu_724_p1 + zext_ln218_1_fu_760_p1);

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state0 = ap_CS_iter2_fsm[32'd0];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

assign ap_CS_iter3_fsm_state0 = ap_CS_iter3_fsm[32'd0];

assign ap_CS_iter3_fsm_state4 = ap_CS_iter3_fsm[32'd1];

assign ap_CS_iter4_fsm_state0 = ap_CS_iter4_fsm[32'd0];

assign ap_CS_iter4_fsm_state5 = ap_CS_iter4_fsm[32'd1];

assign ap_CS_iter5_fsm_state0 = ap_CS_iter5_fsm[32'd0];

assign ap_CS_iter5_fsm_state6 = ap_CS_iter5_fsm[32'd1];

assign ap_CS_iter6_fsm_state0 = ap_CS_iter6_fsm[32'd0];

assign ap_CS_iter6_fsm_state7 = ap_CS_iter6_fsm[32'd1];

assign ap_CS_iter7_fsm_state0 = ap_CS_iter7_fsm[32'd0];

assign ap_CS_iter7_fsm_state8 = ap_CS_iter7_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_279_p2 == 1'd0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_io = ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state8_pp0_stage0_iter7 = ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_condition_1059 = (~((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_279_p2 == 1'd0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((1'b1 == ap_CS_iter7_fsm_state8) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op215_write_state8 == 1'b1) & (out_V_TREADY == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_inElem_1_reg_242 = 'bx;

always @ (*) begin
    ap_predicate_op215_write_state8 = ((icmp_ln290_reg_1066_pp0_iter6_reg == 1'd1) & (icmp_ln249_reg_992_pp0_iter6_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op42_read_state1 = ((icmp_ln253_fu_291_p2 == 1'd1) & (icmp_ln249_fu_279_p2 == 1'd0));
end

assign grp_fu_889_p0 = grp_fu_889_p00;

assign grp_fu_889_p00 = r_V_fu_483_p1;

assign grp_fu_897_p0 = grp_fu_897_p00;

assign grp_fu_897_p00 = r_V_4_fu_524_p4;

assign grp_fu_906_p0 = grp_fu_906_p00;

assign grp_fu_906_p00 = r_V_8_fu_571_p4;

assign grp_fu_915_p0 = grp_fu_915_p00;

assign grp_fu_915_p00 = r_V_2_reg_1085;

assign grp_fu_924_p0 = grp_fu_924_p00;

assign grp_fu_924_p00 = r_V_7_reg_1115;

assign grp_fu_932_p0 = grp_fu_932_p00;

assign grp_fu_932_p00 = r_V_6_reg_1110_pp0_iter2_reg;

assign grp_fu_932_p2 = ((icmp_ln272_reg_1016_pp0_iter4_reg[0:0] == 1'b1) ? 19'd0 : ap_sig_allocacmp_add_i5_i3_870_load);

assign i_2_fu_285_p2 = (ap_sig_allocacmp_i_1 + 22'd1);

assign icmp_ln1039_1_fu_731_p2 = (($signed(add_ln840_8_reg_1240) < $signed(sext_ln1039_1_fu_728_p1)) ? 1'b1 : 1'b0);

assign icmp_ln1039_2_fu_749_p2 = (($signed(add_ln840_8_reg_1240) < $signed(sext_ln1039_2_fu_746_p1)) ? 1'b1 : 1'b0);

assign icmp_ln1039_3_fu_767_p2 = (($signed(add_ln840_8_reg_1240) < $signed(zext_ln1039_fu_764_p1)) ? 1'b1 : 1'b0);

assign icmp_ln1039_4_fu_785_p2 = (($signed(add_ln840_8_reg_1240) < $signed(zext_ln1039_1_fu_782_p1)) ? 1'b1 : 1'b0);

assign icmp_ln1039_5_fu_803_p2 = (($signed(add_ln840_8_reg_1240) < $signed(zext_ln1039_2_fu_800_p1)) ? 1'b1 : 1'b0);

assign icmp_ln1039_6_fu_821_p2 = (($signed(add_ln840_8_reg_1240) < $signed(zext_ln1039_3_fu_818_p1)) ? 1'b1 : 1'b0);

assign icmp_ln1039_fu_713_p2 = (($signed(add_ln840_8_reg_1240) < $signed(sext_ln1039_fu_710_p1)) ? 1'b1 : 1'b0);

assign icmp_ln249_fu_279_p2 = ((ap_sig_allocacmp_i_1 == 22'd4153344) ? 1'b1 : 1'b0);

assign icmp_ln249_reg_992_pp0_iter0_reg = icmp_ln249_reg_992;

assign icmp_ln253_fu_291_p2 = ((ap_sig_allocacmp_nf_2 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln272_fu_341_p2 = ((ap_sig_allocacmp_sf_1 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln290_fu_437_p2 = ((sf_2_fu_431_p2 == 32'd3) ? 1'b1 : 1'b0);

assign icmp_ln302_fu_454_p2 = ((nf_fu_448_p2 == 32'd8) ? 1'b1 : 1'b0);

assign idxprom2_i_fu_682_p1 = nf_2_reg_987_pp0_iter4_reg;

assign local_temp_V_fu_347_p1 = weights_V_TDATA[7:0];

assign nf_3_fu_460_p3 = ((icmp_ln302_fu_454_p2[0:0] == 1'b1) ? 32'd0 : nf_fu_448_p2);

assign nf_fu_448_p2 = (ap_sig_allocacmp_nf_2 + 32'd1);

assign out_V_TDATA = result_V_2_fu_878_p2;

assign p_ZL7threshs_0_address0 = idxprom2_i_fu_682_p1;

assign p_ZL7threshs_1_address0 = idxprom2_i_fu_682_p1;

assign p_ZL7threshs_2_address0 = idxprom2_i_fu_682_p1;

assign p_ZL7threshs_3_address0 = idxprom2_i_fu_682_p1;

assign p_ZL7threshs_4_address0 = idxprom2_i_fu_682_p1;

assign p_ZL7threshs_5_address0 = idxprom2_i_fu_682_p1;

assign p_ZL7threshs_6_address0 = idxprom2_i_fu_682_p1;

assign r_V_4_fu_524_p4 = {{ap_phi_reg_pp0_iter1_inElem_1_reg_242[39:32]}};

assign r_V_8_fu_571_p4 = {{ap_phi_reg_pp0_iter1_inElem_1_reg_242[71:64]}};

assign r_V_fu_483_p1 = ap_phi_reg_pp0_iter1_inElem_1_reg_242[7:0];

assign result_V_2_fu_878_p2 = (add_ln840_13_fu_872_p2 + zext_ln840_1_fu_848_p1);

assign result_V_fu_718_p2 = (icmp_ln1039_fu_713_p2 ^ 1'd1);

assign ret_V_1_fu_606_p0 = ret_V_1_fu_606_p00;

assign ret_V_1_fu_606_p00 = r_V_1_reg_1080_pp0_iter2_reg;

assign ret_V_3_fu_622_p0 = ret_V_3_fu_622_p00;

assign ret_V_3_fu_622_p00 = r_V_3_reg_1090_pp0_iter2_reg;

assign ret_V_5_fu_638_p0 = ret_V_5_fu_638_p00;

assign ret_V_5_fu_638_p00 = r_V_5_reg_1105_pp0_iter2_reg;

assign sext_ln1039_1_fu_728_p1 = $signed(p_ZL7threshs_1_load_reg_1256);

assign sext_ln1039_2_fu_746_p1 = $signed(p_ZL7threshs_2_load_reg_1261);

assign sext_ln1039_fu_710_p1 = $signed(p_ZL7threshs_0_load_reg_1251);

assign sext_ln840_3_fu_692_p1 = add_ln840_2_reg_1195;

assign sext_ln840_4_fu_670_p1 = add_ln840_4_reg_1180;

assign sext_ln840_6_fu_673_p1 = grp_fu_915_p3;

assign sf_2_fu_431_p2 = (ap_sig_allocacmp_sf_1 + 32'd1);

assign tmp_fu_310_p4 = ap_sig_allocacmp_sf_1[1:0];

assign trunc_ln257_fu_322_p1 = ap_sig_allocacmp_sf_1[1:0];

assign xor_ln1039_1_fu_754_p2 = (icmp_ln1039_2_fu_749_p2 ^ 1'd1);

assign xor_ln1039_2_fu_772_p2 = (icmp_ln1039_3_fu_767_p2 ^ 1'd1);

assign xor_ln1039_3_fu_790_p2 = (icmp_ln1039_4_fu_785_p2 ^ 1'd1);

assign xor_ln1039_4_fu_808_p2 = (icmp_ln1039_5_fu_803_p2 ^ 1'd1);

assign xor_ln1039_5_fu_826_p2 = (icmp_ln1039_6_fu_821_p2 ^ 1'd1);

assign xor_ln1039_fu_736_p2 = (icmp_ln1039_1_fu_731_p2 ^ 1'd1);

assign zext_ln1039_1_fu_782_p1 = p_ZL7threshs_4_load_reg_1271;

assign zext_ln1039_2_fu_800_p1 = p_ZL7threshs_5_load_reg_1276;

assign zext_ln1039_3_fu_818_p1 = p_ZL7threshs_6_load_reg_1281;

assign zext_ln1039_fu_764_p1 = p_ZL7threshs_3_load_reg_1266;

assign zext_ln215_fu_724_p1 = result_V_fu_718_p2;

assign zext_ln218_1_fu_760_p1 = xor_ln1039_1_fu_754_p2;

assign zext_ln218_2_fu_778_p1 = xor_ln1039_2_fu_772_p2;

assign zext_ln218_3_fu_796_p1 = xor_ln1039_3_fu_790_p2;

assign zext_ln218_4_fu_814_p1 = xor_ln1039_4_fu_808_p2;

assign zext_ln218_fu_742_p1 = xor_ln1039_fu_736_p2;

assign zext_ln840_1_fu_848_p1 = add_ln840_10_fu_842_p2;

assign zext_ln840_2_fu_858_p1 = add_ln840_11_fu_852_p2;

assign zext_ln840_3_fu_868_p1 = add_ln840_12_fu_862_p2;

assign zext_ln840_fu_832_p1 = xor_ln1039_5_fu_826_p2;

endmodule //MVAU_hls_0_Matrix_Vector_Activate_Stream_Batch
